name: Jenkins Build

on: push

jobs:
  build_jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: Make build call
      run: curl POST http://localhost:8080/job/DevOps%20_HW/build --user user1234:password1234
      
#-H "Authorization:dXNlcjEyMzQ6MTExY2ZiMjQxZGY2YzFmYThiMzJkNzI5NTdkMDU2YTI0Yw==" -X
